### ISSUE TITLE
Templates must contain valid Handlebars: "The partial @partial-block could not be found"

### ISSUE THREAD

**Issue by Cobertos** [TryGhost/gscan#100]
### Issue Summary

When I use the [`@partial-block`](https://handlebarsjs.com/partials.html#partial-block) feature of handlebars I get this error:

GScan Standalone:
![image](https://user-images.githubusercontent.com/6759176/38457211-6641b64a-3a5b-11e8-8d9d-cd4b5c1a9157.png)

```
Checking zip file...

Rule Report:

! Must fix:
- error Templates must contain valid Handlebars

? Consider fixing:
- recommendation <code>package.json</code> property <code>"config.posts_per_page"</code> is recommended. Otherwise, it falls back to 5

✓ 44 Passed Rules

...checks complete.
```

Ghost: 
![image](https://user-images.githubusercontent.com/6759176/38457236-9fa9cbb6-3a5b-11e8-8aaa-206f6dc8d53a.png)

```
Fatal Errors
(Must-fix to activate theme)

Templates must contain valid Handlebars
Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.
See the full list of available helpers here.

Affected files:
partials\header.hbs: The partial @partial-block could not be found
partials\postPartial.hbs: The partial @partial-block could not be found
```

I was previously able to use the [`@partial-block`](https://handlebarsjs.com/partials.html#partial-block) feature of handlebars to pass templates to a partial. Now apparently this does not work in the latest version of Ghost and GScan or even the old version I used to use after I redownloaded (I don't know how I got this to work previously). I did somehow manage to get it on my Ghost Pro blog so it must've worked at some point (cobertos.com)

Ghost Version: `1.22.0` and `1.16.2`
Gscan Version: `1.4.0` and `1.2.1`
Node Version: `8.11.1`

Let me know if this feature is supposed to be supported and if not I'll just close this and I'll switch to a solution that uses two partials.

### Workaround

I came up with a workaround that just involves making two partials that take the same parameters. If you have a `post` partial that uses `@partial-block` like:

```
//In someTemplate.hbs
{{#> postPartial}}
This is {{cool}}
{{/postPartial}}

//In partials/postPartial.hbs
{{> @partial-block}}
```

you would instead do

```
//In someTemplate.hbs
{{> postPartialBegin}}
This is {{cool}}
{{> postPartialEnd}}
```

where `postPartialBegin` contains the content before the `@partial-block` and `postPartialEnd` contains all the content after `@partial-block`

**Comment by kirrg001** [comment]
I currently don't have timt to check/test this. I've never used partial blocks.
Are you getting an error from gscan?

**Comment by Cobertos** [comment]
Yeah, I get it in GScan (running from cli) and also when uploading to a Ghost blog

**Comment by kirrg001** [comment]
And which error? :)

**Comment by kirrg001** [comment]
> The partial @partial-block could not be found

I guess it's this. But can you share the whole error?

**Comment by Cobertos** [comment]
Updated the OP with errors in both Ghost and GScan. Sorry for the late reply, work got super busy on Friday

**Comment by kirrg001** [comment]
We have a list of valid handlebars helpers. I guess this one is just missing, [see](https://github.com/TryGhost/gscan/blob/master/lib/spec.js#L18). PR is welcome 👍

**Comment by gargol** [comment]
As I haven't used partial blocks before neither was digging around for some good resources. For future reference in this was a nice walkthrough with deep dive into different kinds of partials Handlebars use with plenty of samples - https://cloudfour.com/thinks/the-hidden-power-of-handlebars-partials/
