### ISSUE TITLE
GScan 2.0 design and wording

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/gscan#119]
GScan 2.0 will have the ability to choose a version. Therefore we offer a select box now.
Furthermore, the text changed. As a current WIP version, it looks like this:

![image](https://user-images.githubusercontent.com/8037602/43258364-20bfe4b0-9105-11e8-9229-f44ba899d07d.png)

This needs some design and wording refinement (or not, both ways ok)

Note, GScan CSS file lives in ghost.org, but is not referred to directly from GScan, but copied and pasted after each change. See https://github.com/TryGhost/Ghost.org/pull/186

**Comment by JohnONolan** [comment]
ok there are like 5 lines of text all repeating the same thing here

- Delete the red line
- Delete the line below it
- Make sure the select menu has a dropdown arrow to indicate that it is a dropdown
- Change button label from `Upload` to `Start Scanning`

done!

**Comment by JohnONolan** [comment]
(re-assign me if needs more input but this is a pretty simple concept and I think it's easy to understand so should be fine)

**Comment by kirrg001** [comment]
Note: There is a new `2.0` branch in the GScan repository, which contains these changes.

**Comment by peterzimon** [comment]
@AileenCGN agree with John's suggestion. Please let me know when you're ready with your part and I can work on / help out with design refinements.

**Comment by peterzimon** [comment]
@AileenCGN I did the following:

- [x] Delete the red line
- [x] Delete the line below it
- [x] Change button label from Upload to Start Scanning

This one is missing:

- [ ] Make sure the select menu has a dropdown arrow to indicate that it is a dropdown

**Comment by AileenCGN** [comment]
@peterzimon I will try to re-use the code we have for ghost.org/signup where we're using said dropdown arrow.

**Comment by kirrg001** [comment]
Who is working on this?

**Comment by AileenCGN** [comment]
Me! Just needs the dropdown.

Regarding wording, I opened a new topic in the forum and will post what we have already tomorrow, so we can finalise the wordings for all checks. Those are easy to change, but not all there yet.

**Comment by AileenCGN** [comment]
Somehow didn't get closed automatically.

Fixed with https://github.com/TryGhost/gscan/commit/59b9e643287887d8f986959fc91d6b82061897f1
