### ISSUE TITLE
GScan should be able to remove checks from previous major versions

### ISSUE THREAD

**Issue by aileen** [TryGhost/gscan#135]
The current logic in GScan 2.0 adds new rulesets on top of the old rulesets. There is currently no way to remove a rule, template, or known helper, that we don't want to check for anymore in the latest version.

**Comment by AileenCGN** [comment]
@gargol assigned you to this now, as I assume you're going through the GScan issues now?

**Comment by gargol** [comment]
yup! thanks @AileenCGN :+1:

**Comment by naz** [comment]
It is possible to remove the rules by "removing" them from the "previousRules" set. An example of such removal [is here](https://github.com/TryGhost/gscan/commit/e27e6435e2745f66382ca0c181334f91a5c42fcf).
