### ISSUE TITLE
Detect `{{error.statusCode}}` and deprecate

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#137]
`{{error.statusCode}}` is deprecated.

Tell user to use `{{error.code}}`.

Deprecate in GScan 2.0.

**Comment by kirrg001** [comment]
Can we close this?:)

**Comment by AileenCGN** [comment]
@kirrg001 Any clue, why the issues don't get closed automatically?

![image](https://user-images.githubusercontent.com/8037602/44033123-f997d4c0-9f3b-11e8-9af1-0bfc06313b3d.png)

Closed with 1314ad3c0c4fa51a2e5230f9a03b1e0094cffd14

**Comment by kirrg001** [comment]
I think it's because it wasn't merged into master.
