### ISSUE TITLE
Ghost 3.0 gscan changes

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/gscan#144]
### Running v3 rules (`--canary` flag feature)

This flag is needed to allow us testing gscan v3 rules before Ghost v3 is released.

The file with `canary` definitions can be aliased to `--v3` flag, so as we near new version release, we could make it possible to do `gscan --canary` or `gscan --v3`, so that theme developers can have their themes ready against any known changes way ahead of the release.

`canary` spec will exist perpetually (similar to `/canary/` API in Ghost) out of which stable v3/v4 etc. specs will be branched once they reach stability.

Todos:
- [x] add `--canary` option in CLI
- [x] add `Canary (next)` option in Web interface
- [x] make it possible to pass `vX` (`v2`, `v3`) option for `check` function in `checkVersion` options parameter
- [x] add `canary` rule -  warning to check for missing `engines` flag in `package.json` so the API is "falling back" to the default version (https://github.com/TryGhost/gscan/pull/255). 
- [x] update wording in `canary` for to `users` -> `authors` deprecation rule (GS001-DEPR-USER-GET') as this alias has been removed completely (this shoudl be clarified in the update) (https://github.com/TryGhost/gscan/pull/256)
- [x] detect "ghost-api === v1" used in pakcage.json (https://github.com/TryGhost/gscan/pull/258)
- [x] override `GS001-DEPR-ESC` and deprecate use of `{{(error.)?code}}` helper instead of `{{statusCode}}` (https://github.com/TryGhost/gscan/pull/259)
- [x] add "bookmark card classes" rules
- [x] reword rules using "Ghost 2.0" wording
  - [x] check `GS002-DISQUS-ID` and `GS002-ID-HELPER` using "Ghost v1.0" wording

Post v3 release:
- [ ] prepare v3 (out of `canary` rules) set of rules becoming a default (latest) version on a `v3` branch (will release 3.0.0 out of this branch)
  - [x] change Ghsot core from using `canary` flag to default once switched to `gscan 3.0.0` (https://github.com/TryGhost/gscan/pull/257)
  - [ ] merge ^ into master
- [ ] Update details for {{subscribe_form}} deprecation

NOTE: the initial issue was more like a note and can be checked for reference in history.

**Comment by gargol** [comment]
First rules to be added as fatal for v3.0 can be based on https://github.com/TryGhost/gscan/issues/181 and https://github.com/TryGhost/gscan/issues/174.
