### ISSUE TITLE
GScan CLI is outputting html

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#148]
This exists for a while.
It's caused by the fact that the rules in GScan define html by default.

**Comment by gargol** [comment]
@kirrg001 my understanding is we want to changes `rule` and `details` contents (https://github.com/TryGhost/gscan/blob/master/lib/specs/latest.js#L21-L22) from HTML to something that could be universally interpreted by web UI, CLI output and when used directly as a library? Has any research been done into this or any ideas on how to best solve this problem?

**Comment by kirrg001** [comment]
Yeah exactly e.g. the CLI/Ghost receives HTML from GScan.

> Has any research been done into this or any ideas on how to best solve this problem?

Hmm I don't think so. This popped out while working on 2.0.
