### ISSUE TITLE
Update version dropdown in UI

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#161]
Instead of showing specific Ghost versions e.g. `2.1.1` or `2.2.10098` in the dropdown, we would like to simplify the UI a little, because we have to bump [this file](https://github.com/TryGhost/gscan/blob/v2.2.1/lib/utils/versions.json) before **any** GScan release.

@JohnONolan suggested to choose

Latest

`2.x`
`1.x`

@AileenCGN If we change this, when do we have to update [this file](https://github.com/TryGhost/gscan/blob/v2.2.1/lib/utils/versions.json) at all?

**Comment by AileenCGN** [comment]
@kirrg001 That was my lack of documentation here. Here's how this file works:

`major`: should aways list the major version and shall not be updated unless we do a major jump. This means it always stays as `1.0.0` or `2.0.0` and so on. This is the visible version to the user. Of course we can change that to `2.x` to prevent confusion, but the intention was not to update this (therefore the name `major`).

`docs`: this is actually used to generate the links to themes.ghost.org and therefore needs to be updated whenever we release a new version in our themes documentation.
