### ISSUE TITLE
gscan warns about {{author}} on author-:slug.hbs templates

### ISSUE THREAD

**Issue by jameshome** [TryGhost/gscan#165]
I'm using default Ghost routing to have custom author pages for each author. gscan doesn't seem to parse these as author pages, so it is showing these as errors. Is there something different I should be doing to tell gscan about these custom author pages, or is this a bug?

**Comment by zce** [comment]
This problem also happened when `{{author}}` on partial templates as data context.

**Comment by zce** [comment]
This problem also happened when `{{author}}` on partial templates as data context.

```
Rule Report for v2.1.0:

! Must fix:
- error Replace the <code>{{author.cover_image}}</code> helper with <code>{{primary_author.cover_image}}</code> or <code>{{authors.[#].cover_image}}</code>
    Files: partials/site-cover.hbs
```

**Comment by kirrg001** [comment]
Thanks for the bug report 👍 

Looks like this is caused by [this line](https://github.com/TryGhost/gscan/blob/master/lib/specs/latest.js#L57). We allow `{{#author}}` in `author.hbs`, but not in `author-slug.hbs`.

**Comment by gargol** [comment]
This issue very closely related and will be solved as a part of https://github.com/TryGhost/gscan/issues/170.
