### ISSUE TITLE
Update gscan docs URL

### ISSUE THREAD

**Issue by naz** [TryGhost/gscan#178]
### State
Currently, we are [linking](https://github.com/TryGhost/gscan/blob/ab44dc3/lib/specs/latest.js#L4) to the old themes docs site `https://themes.ghost.org/docs/` when providing a help link in "latest" warnings. 

### Problem
This relies on redirects being set up from e.g. `https://themes.ghost.org/docs/blog` to `https://docs.ghost.org/api/handlebars-themes/helpers/site/` and requires to knowledge about redirects instead of using original link.

### Solution
Link to current docs site - ~`https://docs.ghost.org/`~ `https://ghost.org/docs/themes/`  instead of `https://themes.ghost.org/docs/`

### Extra
Remove [this comment](https://github.com/TryGhost/gscan/blob/ab44dc3/lib/specs/latest.js#L367) and check for other places that use `themes.ghost.org` (like [here](https://github.com/TryGhost/gscan/blob/776ba8ecb0cac729b3efdc556ccbb4620b4257e6/app/tpl/index.hbs#L15), [here](https://github.com/TryGhost/gscan/blob/2c4a7be16743a70a0acba4b8e2f2f5c798ac2c36/lib/specs/v1.js#L7))

**Comment by naz** [comment]
There has been a report of a broken link in members rule. This issue _might be_ the root cause.
<img width="506" alt="screenshot-12-15-18-30-03-2022" src="https://user-images.githubusercontent.com/675397/160955082-bcefbf91-1b89-4632-ba99-dc7d143e887b.png">

**Comment by naz** [comment]
While looking into older rule found other broken URLs. E.g. for `GS001-DEPR-CON-TSIMG` from `v1` spec we generate following URL: https://ghost.org/docs/api/handlebars-themes/context/tag/context/tag/#tag-object-attributes, which returns 404.

Other helpers like `GS040-GH-REQ` return a valid URL like https://ghost.org/docs/api/handlebars-themes/helpers/ghost_head_foot/ , which passes through a redirect and resolves to https://ghost.org/docs/themes/helpers/ghost_head_foot/.

Note, for a v2 rule which is similar to an example 404 above, the url https://themes.ghost.org/v1/docs/context/author after a redirect at least resolves to general theme documentation https://ghost.org/docs/themes/. Way better than 404.

@aileen do you have access to redirects for ghost.org? Maybe we could do something smart about the 404 described above.

**Comment by aileen** [comment]
@naz instead of using redirects, can we not just update the links to point to the correct place? Feels like we're creating our own problems when creating redirects for link that we are in control of.

Or is this because of older versions of gscan which are used in older versions of Ghost which we don't update anymore?

**Comment by naz** [comment]
I had in mind the latter usecase - old Ghost versions. Although thinking about it again, maybe we can be more loose with those old versions. The EOL for Ghost 3.x was Jan 2022:
![Screenshot from 2022-04-04 08-56-54](https://user-images.githubusercontent.com/675397/161457581-5304ec39-f6a8-453d-87cb-f9e178c665f4.png)

@ErisDS should we update the help links in gscan error details to direct to whatever best is available and maybe fallback the not found to https://ghost.org/docs/themes/? Could also set up a single catch-all redirect the `/docs/themes/` if the old format of the docs URL is detected after we update gscan. Maintaining the old redirects up to date is a hassle with unclear, almost negligible ROI, based on no major complains.

**Comment by ErisDS** [comment]
I think the answer here is we should do both. The links in the latest gscan should match up with their latest location.
Meanwhile, we should have redirects to fix old links.

Old redirects should be kept unless @kymellis says they can be removed. They are an SEO exercise first and a usability on second.

**Comment by ErisDS** [comment]
Is there anything left to do here?

**Comment by aileen** [comment]
@ErisDS This is fixed and shipped!
