### ISSUE TITLE
Support running checks against a GitHub repository

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/gscan#3]
At the moment, you can use gscan by uploading a zip file to the web interface, or by providing a local path to a folder or zip on the command line.

Ideally, we'd also support supplying a GitHub repository, both via the web interface and via the cli.

**Comment by acburdine** [comment]
Cool, will get to this in a couple of days hopefully :smile:

**Comment by ErisDS** [comment]
With the advent of GitHub Actions, it's already super easy to do this. Also wiring up actions gives you a proper CI tool, which is way better that being able to do a one-off run against GitHub from a CLI/website.

If you do want to do a one-off you can always download the zip from GitHub.

I don't think this is worth leaving open, especially as noone has really asked for this ever.
