### ISSUE TITLE
cli no longer accepts arguments in Linux

### ISSUE THREAD

**Issue by ojeytonwilliams** [TryGhost/gscan#307]
Steps to reproduce:

```
npm install -g gscan@latest
gscan .
```
see
```
/usr/bin/env: ‘node --no-warnings’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

it seems problem is that Linux only allows one argument to be passed after `#!` (discussed [here](https://unix.stackexchange.com/questions/399690/multiple-arguments-in-shebang)), so it's ignoring everything after `--no-warnings`.  Getting rid of that fixes it, anyway!

**Comment by daniellockyer** [comment]
Thanks for the report @ojeytonwilliams! :smile:

**Comment by ojeytonwilliams** [comment]
You're welcome @daniellockyer and thanks, the new version works perfectly!
