### ISSUE TITLE
Gscan Latest version not working

### ISSUE THREAD

**Issue by mskian** [TryGhost/gscan#309]
`gscan` latest package not working
when try to test end up with

```sh
gscan --fatal --verbose .
/usr/bin/env: invalid option -- 'S'
Try '/usr/bin/env --help' for more information.
```

```sh
gscan .
/usr/bin/env: invalid option -- 'S'
Try '/usr/bin/env --help' for more information.
```

Live-action - https://github.com/TryGhost/London/runs/576771741

issue on `3.5.1`
`3.4.0` works well

**Comment by gargol** [comment]
Hey @mskian, could you please provide the information on the environment (OS, node version, etc.) you are running the command in?

**Comment by mskian** [comment]
OS: ubuntu 18.04 LTS
Node: v10.20.0
ghost: 3.13.1
Ghost-CLI version: 1.13.1

**Comment by mskian** [comment]
I think due to this - https://github.com/TryGhost/gscan/commit/7954aee85c5fb438b161b6a0bded1cb2d2aea4b9

**Comment by mskian** [comment]
`gscan/bin/cli.js`

```sh
#!/usr/bin/env node
const prettyCLI = require('@tryghost/pretty-cli');
const ui = require('@tryghost/pretty-cli').ui;
const _ = require('lodash');
const chalk = require('chalk');
const gscan = require('../lib');

```

I tried this
this will work

**Comment by ErisDS** [comment]
@daniellockyer can you do a little bit more looking into this to see if there's another method to get rid of the warning, and if you can't find one in an hour or so lemme know? 

Last resort I'll try to refactor the output so the warning doesn't look like part of the gscan output

**Comment by daniellockyer** [comment]
@ErisDS Can't find anything :frowning_face: 

https://www.xiaoru.li/post/disabling-node-warnings/ mentions the same issue:

```
If you only wanted to disable the warnings because you used the fs.promises API as I did, I would recommend you to wrap the original APIs in a promise manually next time to avoid the hassle, or simply sticking to util.promisify as well as the sync version of the APIs, instead of using this workaround.
```

**Comment by ErisDS** [comment]
Yeah - but we're not using the fs.promises API, a dependency 3 levels deep is :(

**Comment by ErisDS** [comment]
I've raised this as an issue against Node.js: https://github.com/nodejs/node/issues/32876

We obviously need this working on ubuntu, I'll take a look to see if I can minimize the impact of the warning.

**Comment by markmssd** [comment]
Ran into the same issue, glad I wasn't crazy! I had to downgrade to `3.4.1` to have it work.

**Comment by ErisDS** [comment]
After a bit of a back-and-forth, we've found an OS-agnostic solution using `process.removeAllListeners()`

Fix and release incoming!

**Comment by markmssd** [comment]
Working with this fix, thank you @ErisDS !
