### ISSUE TITLE
uploading an image crashes gscan

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#35]
When you upload an image, gscan can't handle this case. It crashes somewhere in the extract-zip logic. 

What we need is: add mime-type and file-type validation into the upload process.

**Comment by ErisDS** [comment]
@kirrg001 I assigned this because it looks like you may have an incoming PR for it (and if not then the issue should probably be expanded instead 😜)

**Comment by ErisDS** [comment]
This was fixed a long time ago.
