### ISSUE TITLE
bypass escaping handlebars

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#37]
Any field has the possibility of opening an XSS if the theme bypasses escaping.

Reference:
http://stackoverflow.com/questions/27926605/handlebars-triple-stash-to-avoid-escaping-html-entities

Suggested by @sebgie

**Comment by ErisDS** [comment]
It is not clear what this issue is about 😉  am I right in thinking it is a request for a check for triple-braces?

**Comment by kevinansfield** [comment]
I think so, that's what was mentioned in Slack 😄

**Comment by kirrg001** [comment]
Exactly 👍 

`Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash", {{{.`

From http://handlebarsjs.com/#html-escaping

**Comment by ErisDS** [comment]
We've never had an issue or vuln report that would be solved by this. Not sure it's useful
