### ISSUE TITLE
Default version isn't consistent

### ISSUE THREAD

**Issue by tpatel** [TryGhost/gscan#372]
I’ve noticed that the default ghost version for gscan is sometimes `v3`, sometimes `canary` depending on files:
https://github.com/TryGhost/gscan/blob/43c5b611f8b5b6a3a5377827b9f72a6105396f49/lib/checks/001-deprecations.js#L7
https://github.com/TryGhost/gscan/blob/43c5b611f8b5b6a3a5377827b9f72a6105396f49/lib/checks/010-package-json.js#L144

And depending on whether it's run through cli, the embedded express app or as a library:
https://github.com/TryGhost/gscan/blob/43c5b611f8b5b6a3a5377827b9f72a6105396f49/bin/cli.js#L67
https://github.com/TryGhost/gscan/blob/43c5b611f8b5b6a3a5377827b9f72a6105396f49/app/index.js#L52
https://github.com/TryGhost/gscan/blob/43c5b611f8b5b6a3a5377827b9f72a6105396f49/lib/checker.js#L21

I'm suggesting we use `canary` as the default everywhere to avoid extra maintenance when changing version. cc @naz @daniellockyer

**Comment by ErisDS** [comment]
Defaulting to canary sounds good but also making this not a hardcoded string would be great!

**Comment by tpatel** [comment]
This was solved in https://github.com/TryGhost/gscan/commit/03264063bb462c4ff0c143fc2261e5d30d90be1e. I've chosen to use the `versions.json` file to host this extra constant.
