### ISSUE TITLE
@partial-block

### ISSUE THREAD

**Issue by IamTheLime** [TryGhost/gscan#417]
Handlebars {{ @partial-block }} is broken in the latest version of ghost, gscan is identifying this helper as a handlebars error.

Downgrading gscan, in the docker container will allow you to load the website without loss of functionality.

**Comment by benshaaw** [comment]
We have confirmed that this breaking change happens in-between `gscan` versions `4.1.0` and `4.1.1`, tested on a local `ghost:4-alpine` container and rebuilding the `node_modules` dir after changing `gscan` version pins.

**Comment by benshaaw** [comment]
Theme validating successfully with changes shown in this PR

https://github.com/TryGhost/gscan/pull/418

**Comment by tpatel** [comment]
I've made a minor change to https://github.com/TryGhost/gscan/pull/418 and pushed it, thanks for your contribution @benshaaw.

This is released in gscan `v4.16.1`, and I'll merge that in Ghost for the next release.

**Comment by tpatel** [comment]
This was released in Ghost v4.28.0 https://github.com/TryGhost/Ghost/releases/tag/v4.28.0
