### ISSUE TITLE
Support for Github repository. 

### ISSUE THREAD

**Issue by varadekd** [TryGhost/gscan#518]
I noticed in the Readme that scanning isn't supported using the Github repository. I'm considering developing this feature. Should I follow a specific process for shipping this feature? Do I need to submit a proposal first, or can I simply build it and create a PR?

**Comment by varadekd** [comment]
@JohnONolan Can you help me with this issue? or tag someone who will help me with this query

**Comment by JohnONolan** [comment]
I'm not sure I understand what you mean. Can you explain what the feature is that you're proposing?

**Comment by varadekd** [comment]
Hi @JohnONolan,

Sorry for any confusion caused. I am planning to develop the functionality that allows gscan to fetch content using a Github URL. My question is, do I need to submit a written document first to propose and build this feature, or can I go ahead and start building it?

**Comment by varadekd** [comment]
@JohnONolan Waiting for your reply on this. I hope my comment is much clear now

**Comment by JohnONolan** [comment]
You mean adding a GitHub URL as an input to the web version, so people can use that rather than uploading a zip? If so, sure go for it. Feel free to submit anything in advance if you want feedback before building, otherwise happy to offer feedback on a PR

**Comment by varadekd** [comment]
I am closing this issue since my requirement are met.
