### ISSUE TITLE
Please upgrade your dependency on require-dir to 0.3.2

### ISSUE THREAD

**Issue by Xaekai** [TryGhost/gscan#56]
It breaks this package on Node 8 because of [this bug](https://github.com/aseemk/requireDir/issues/45)

**Comment by MatTheCat** [comment]
In the meantime you can edit *npm-shrinkwrap.json* replacing 

```json
"require-dir": {
    "version": "0.1.0",
    "from": "require-dir@0.1.0",
    "resolved": "https://registry.npmjs.org/require-dir/-/require-dir-0.1.0.tgz"
}
```

with

```json
"require-dir": {
    "version": "0.3.2",
    "from": "require-dir@0.3.2",
    "resolved": "https://registry.npmjs.org/require-dir/-/require-dir-0.3.2.tgz"
}
```

and then rerun `GHOST_NODE_VERSION_CHECK=false npm install  --production`

**Comment by ErisDS** [comment]
To clarify, node 8 is not officially supported by Ghost yet: https://docs.ghost.org/docs/supported-node-versions

The Ghost team will start looking at adding tests and fixing bugs for Node 8 within the next few months, so that we are ready for when v8 [becomes LTS](https://github.com/nodejs/LTS) in October. 

In the meantime, PRs are very welcome 😊

**Comment by Xaekai** [comment]
I'm aware Ghost doesn't support Node 8 yet, but in the meantime I desire to run it under Node 8 anyway. The host I have my Ghost blog under is a shared space for all my Node services and all of them run under 8 just fine. And I don't want to have to spin up another VPS just for my blogs or deal with the minefield of pain that is `nvm`. I'd lose the pretty unified output I get from PM2 :cry: 

And more importantly, this is the **sole issue** I had getting Ghost to run on Node 8. After forcing this package to use the newer `require-dir` everything *seems* to work fine. So I have this already solved locally and anyone else needing to do the same for pragmatic reasons can use MatTheCat's suggestion.

I don't fault Ghost for following the LTS model. But it just isn't feasible for me to use babel on all my pet projects just for Ghost.

I will look into seeing in it's a simple drop in upgrade or if there are any gotchas and submit a PR in the next few days.

**Comment by kirrg001** [comment]
https://github.com/TryGhost/gscan/commit/60385bc95dbe6ee21e4ef76787dc9807d5b1f5d7
