### ISSUE TITLE
Regex helper lookup for deprecations misses handlebars edge cases

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/gscan#62]
There are several edge cases that the regular expressions used to look for deprecated helpers and data properties will not catch.

For example, it's valid to have whitespace: `{{ @blog.cover }}`, the image helper accepts arguments `{{image absolute="true"}}` and there are other paths that could be used to reference an image property, e.g. `{{../image}}` or `{{post.author.image}}` or `{{post.tags.[0].image}}`.

The regular expressions will catch some 80% of common cases, however they will leave many incorrect usages of various deprecations. In the case of images, which we need to count as fatal errors, I think we need a more robust solution.

- [x] mark image deprecations fatal
- [x] extend the existing regex to support more use cases (or go with compiler api rewrite)

**Comment by ErisDS** [comment]
I had an idea, which may work, to leverage the handlebars compiler by passing in fake data and some fake helpers, so that we test rendering templates under psuedo-ghostlike conditions, and then check the output.

There are serious challenges in both the regex and compiler approaches.

Using regex as we are right now, we need to approximate all possible handlebars expressions that could result in an image being output. For detection, we might get quite close, but note: if we try to write anything which attempts to fix the issue, it also needs to be aware of context and that is really really hard without proper parsing / state machines.

Using the compiler approach, we need to approximate the conditions of Ghost, including faking at least the foreach & image helpers and the data passed in and making sure that there is enough fake data present that conditionals won't get in the way. The problem is that code branches (if/else) are dependent on data, so even with this technique, it would be near impossible to catch every case.

Two other possible approaches are:

- inspect the compiled template function without passing data to see if we can interpret the templating functions - e.g. use handlebars' "precompile" option. I have tried this before without much success

- write our own parser with states to detect the context in which the image helpers are called. What to say about this? Writing parsers is hard & handlebars is not that small!

If you want to get super nerdy about this, the tokenizer for handlebars itself is here: https://github.com/wycats/handlebars.js/blob/master/src/handlebars.l - this is largely uncommented and therefore unintelligible but it does serve as a blueprint for what is considered a handlebars expression.

There is also a bunch of information about the compiler APIs and tooling that is available in handlebars here: https://github.com/wycats/handlebars.js/blob/master/docs/compiler-api.md

**Comment by kirrg001** [comment]
Thanks for the bug report 👍 

I would suggest to extend the existing regex before releasing 1.0, by this we can cover many more cases. Even with your new suggested approach we can miss cases or there is the chance to introduce new bugs.

> {{ @blog.cover }}

We already support white spaces for `pageUrl` helper. We can do that here and in the other deprecation checks as well. Good catch!

> {{image absolute="true"}}, {{post.author.image}} etc.

Can be covered by modifying the existing regex.

> {{../image}}

I never saw this notation and i also can't find it anywhere in the documentation. Could you please explain what this does?

**Comment by ErisDS** [comment]
@kirrg001 handlebars path expressions provide for many different ways in which properties inside the JSON structure can be referenced from various locations.

If you are inside one nested object, you can reference the object above using `{{../property}}` and this works like paths in an OS `../../../` both Casper 1.0 and 2.0 use this construct.

See these pages of the docs: http://handlebarsjs.com/#paths and http://handlebarsjs.com/expressions.html

**Comment by ErisDS** [comment]
I think that https://github.com/wycats/handlebars.js/blob/master/docs/compiler-api.md may hold the key. There are some tools available which interact with parsed templates & the compiler, that I have not tested out yet. 

If we are doing an investigation into the feasibility of fixing certain issues in themes, we have to be able to understand context, and regexes will not get us there.

**Comment by kirrg001** [comment]
In my opinion, the compiler api can only cover wrong handlebars helper, but it can **not** cover all edge cases for deprecated image property access. And i think that deprecated property access () is what most of the edge cases reflect. And that means, rewriting what we have to use the compiler api, still leaves us with all the edge cases for image property access.

**Keep in mind that:**

`{{ image }}` or `{{image}}` or `{{image absolute=true}}` can't be detected from a handlebars compiler as a wrong handlebars helper! Handlebars can't know if this is a property or a helper. That's why it can only detect `{{image "string"}}` as a wrong template helper.

**Comment by ErisDS** [comment]
> can't be detected from a handlebars compiler as a wrong handlebars helper

In this case, that doesn't really matter as image is both a helper and a property. So even if it could detect the helper part, we'd still be stuck trying to detect properties. 

-----

I have been thinking about this, and I think I've managed to break down the problem more clearly.

To start with - there are 2 problems

A. detecting usages of the image helper/properties
B. detecting the context of each usage

Assuming both are important, I think we can then classify instances of "image" in levels of how common they might be used.

**Level 1: simple path expressions which contain the context**

E.g. `{{author.image}}` 

Trivial to detect the usage and the context as they are both present

**Level 2: the image helper**

E.g. `{{image}}` or `{{image absolute="true}}` or even `{{image imadethis="up"}}`

Trivial to detect usage.
Very hard to detect context, made extra hard if used inside a partial without context.

**Level 3: complex path expressions with context**

E.g. `{{../author.image}}` or `{{post.tags.[0].image}}`

Relatively straightforward to detect, using more advanced regexes.
Once we have a matching regex, straightforward to find the context.

**Level 4: complex path expression with no context**

E.g. `{{../image}}` or `{{../.[10].image}}`

Relatively straightforward to detect, using more advanced regexes.
Very very hard to detect context.

_Note: all examples have no whitespace, assume we will use regexes which do handle whitespace_

Given these levels, we can see that it should be possible to write a regex which detects them. For levels 2 and 4 the regex should also be able to tell us the context.

From the perspective of any attempt to fix the usages:

For level 2, it will be impossible to determine context using regex alone, especially in the case of partials. I think the only reliable way to detect the context would be with a state machine parser.  

I would suggest that level 2 inside a partial and level 4 are all usages that can be detected but not automatically fixed.

----

Making decisions:

I'd suggest to start with writing a regex for each level & running this against themes to detect how common each case is in templates & partials. Might be that 3 and 4 are so rare they can both be errors. Might be that level 2 inside a partial is super common and we need to rethink.

**Comment by ErisDS** [comment]
Is there anything left to do here or can this be closed?

**Comment by kirrg001** [comment]
We kept the issue open in case we would like to implement the alternative solution. But we can re-open if we want to. Closing.
