### ISSUE TITLE
Unkown helper not always detected when within context

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/gscan#63]
I've stumbled over an inconsistency. While intentionally using unknown hbs helpers in themes, I found that they sometimes get detected and sometimes not. The reason for that is the context they are in. A helper that is definitely wrong e. g. `{{bla "string"}}` is not detected within e. g. `author` context.

---

### Example that works fine in `author.hbs`:

![image](https://user-images.githubusercontent.com/8037602/27617424-6895c9f4-5be0-11e7-8ef8-658fa551cc44.png)
*Note, that this ^ is within the `author` context!!*

#### Example theme:
[casper.zip](https://github.com/TryGhost/gscan/files/1104961/casper.zip)

#### Output:

*Output, when outside of `author` context*:
![image](https://user-images.githubusercontent.com/8037602/27617541-35ee88c8-5be1-11e7-9ac2-df7ac9417e06.png)

*Output when inside of `author` context*:
![image](https://user-images.githubusercontent.com/8037602/27617674-f75ddf90-5be1-11e7-9521-c4fec66986b2.png)

---

### Example, where it fails, detecting wrong helpers in `author.hbs`:

![image](https://user-images.githubusercontent.com/8037602/27617492-dc7aee30-5be0-11e7-8ecd-d62353e215c7.png)
*Note, that this ^ is outside of the `author` context.

#### Example theme:
[Ghostly-master 2.zip](https://github.com/TryGhost/gscan/files/1104963/Ghostly-master.2.zip)

#### Output:

*Fails to detect wrong helper, when within `author` context*:
![image](https://user-images.githubusercontent.com/8037602/27617509-fa92ee68-5be0-11e7-8401-34f3542c73b2.png)

*Detection works in this theme, when outside of `author` context*:
![image](https://user-images.githubusercontent.com/8037602/27617610-b0ee167e-5be1-11e7-9ce1-c9e21cbf109c.png)

**Comment by ErisDS** [comment]
@AileenCGN can you please provide the example code that generates an unexpected output, and also what the output is, and what is unexpected about it?

**Comment by AileenCGN** [comment]
@ErisDS Thanks for the suggestion! I updated the issue description and provided more information.

**Comment by cobbspur** [comment]
This is because no data is being passed to the template, therefore blocks like author are not executed.

Also partials content is not added when the partial is registered.
