### ISSUE TITLE
Path issue with partials on Windows

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/gscan#64]
A user got this error when trying to start Ghost Beta.2

![image](https://user-images.githubusercontent.com/101513/27605362-61a61a52-5b74-11e7-98db-f047b404d2cd.png)

The error appears to be a problem with paths to partials on windows.

- reference partial is `partials\\floating-header.hbs` (not sure why there are 2 slashes)
- error message talks about the partial `icons/point` (slash is forward... Windows not like this)

I am not 100% if this is a gscan bug, but as Casper 2.0 is working in all of my tests on mac&linux it would make the most sense that there is some missing place in gscan where we need to add some extra windows handling.

I'm pretty sure that nested partials works on windows normally...

Steps to reproduce:
- use windows
- install latest release from the zip
- start ghost

OS: Windows 10.0.15063 x64

**Comment by kirrg001** [comment]
Hmm we should make the red error color a litte bit brighter 😬

**Comment by evilpilaf** [comment]
@kirrg001 it's my console emulator on windows that has the transparency and makes the red les bright 😄
