### ISSUE TITLE
Old {{image}} helper is not being detected within a partial file.

### ISSUE THREAD

**Issue by biswajit-saha** [TryGhost/gscan#67]
I was updating a old theme so that it can be compatible with Ghost 1.0.0. I have found this issue. If it's intended behavior then feel free to close this issue.

### Exact case

I have `{{tag.image}}` within a partial file named **cover-tag.hbs** . Which is being called within **tag.hbs** file.

As we know, In ghost 1.0.0 `{{image}}` or in this case `{{tag/image}}` can not be used. So gscan should show error or warning. But If I upload the theme including this code there is no error or warning. Theme check passed.

**Code in the cover-tag.hbs file**

```
<div class="row cover tag-cover {{#if tag.image}}" style="background-image: url({{tag.image}}) {{else}}no-image{{/if}}">
	<div class="col-md-12 cover-inner">
		<h3 class="tag-name">
			Tag: {{tag.name}}
		</h3>
		<div class="post-count">
			Total {{plural pagination.total empty='0 Post' singular='% Post' plural='% Posts'}}
		</div>
		{{#if tag.description}}
		<div class="tag-description">
	        {{tag.description}}
		</div>
		{{/if}}
	</div>
</div>
```

**Code in tag.hbs file where cover-tag.hbs file is being called**

```

{{!< default}}
{{! The tag above means - insert everything in this file into the {body} of the default.hbs template }}

<div class="content-area-wrap">
	{{> mobile-header}}
	<!-- start main content -->
	<div class="container-fluid main-content-wrap">
		{{> cover-tag}}
		<div class="row posts-wrap-outer">
			{{#foreach posts}}
			<!-- start post -->
			.............................................................................................................
			...........this part of code is not relevant for this issue ...........................
			.............................................................................................................
			<!-- end-post -->
			{{/foreach}}
		</div>
		{{pagination}}
	</div>
	<!-- end main content -->
</div>
```

**Passed when uploading in to Ghost dashboard** 

![after upload](https://user-images.githubusercontent.com/17477852/27732002-1c45fcd0-5dad-11e7-8ff6-938ba61b1406.png)

**Passed when uploading in to gscan.ghost.com** 

![theme check passed](https://user-images.githubusercontent.com/17477852/27731950-d9c2107e-5dac-11e7-8559-6d4c53e0034f.png)

**Comment by cobbspur** [comment]
Thanks for the report, this will be fixed with an upcoming PR. The regex for tag.image was missing so would fail or rather NOT fail no matter which file it was in.
