### ISSUE TITLE
Handle themes with custom helpers

### ISSUE THREAD

**Issue by felin-arch** [TryGhost/gscan#86]
Currently gscan will throw a **ThemeValidationError** when using a theme with custom Handlebars helpers, even if those helpers are added by apps.

**Detailed error:**
fatal: true
level: error
rule:  Templates must contain valid Handlebars
message: Missing helper: "ifeq"
code: GS005-TPL-ERR

The theme works fine in development as processing is not terminated, but breaks in production. I am not sure about the good solution here. 

I checked out gscan's code and it seems like *lib/checks/005-template-compile.js* should register the helpers from installed apps as well when running the validation. Currently, I am running a custom patched version of the *spec.js* file, which allows for the custom helpers.

Here is the template I am using: https://github.com/judge/security-drops
Here is the helper repo: https://github.com/felin-arch/security-drops-helpers

**Comment by kirrg001** [comment]
Hey @felin-arch! 

Thanks for your report!

Apps are [not officially supported yet](https://apps.ghost.org/) and the [wiki document](https://github.com/TryGhost/Ghost/wiki/Apps-Getting-Started-for-Ghost-Devs) had the purpose to share a demo idea for contributors to work on. **Before we can e.g. support gscan to register app helpers, we need to officially support apps.**

> I am running a custom patched version of the spec.js file, which allows for the custom helpers.

That makes sense 👍  Happy to hear you found a workaround.

---

I am going to close this issue. It's labeled so we can re-open in the future in case we find a contributor who will reconsider & revalidate apps.

**Comment by felin-arch** [comment]
Thanks for getting back so quickly. I completely agree with the closing, I opened the ticket to have a reference. Hopefully, it will save some time for others as well.

**Comment by joakimkm** [comment]
Hey felin-arch. Did you find any good solution for this? Had been nice to get it done without having to edit core-files.

**Comment by felin-arch** [comment]
@joakimkm, sadly I did not. I am still running a patched spec.js found at `node_modules/gscan/lib/spec.js`. I reapply the patch after each update.

**Comment by dasilvacontin** [comment]
To anyone trying to find where is the `gscan` that their Ghost is using, it should be somewhere like this:
`vim versions/3.40.1/node_modules/gscan/lib/specs/v1.js`.

So inside the versions folder, inside whichever Ghost version you are using, etc.
