### ISSUE TITLE
Gscan read-theme regex bug

### ISSUE THREAD

**Issue by marius-ionescu** [TryGhost/gscan#92]
You have a bug here:
https://github.com/TryGhost/gscan/blob/c98f0d57a037b38b41ce01ffdf6391de3fafd972/lib/read-theme.js#L156

Specifically you're asserting the position at the start of the string only for post- not for page- and custom-

That will mean things like: partials\page-whatever -> will trickle down to generateSlug which will generate InternalServerError: Cannot read property '2' of null.

It's a quick fix and I can raise a PR if you want to

**Comment by kirrg001** [comment]
Hey!

First of all, please read the definition of partials [here](https://themes.ghost.org/docs/structure#section-partials). 

Furthermore, custom templates are only supported in the root level of your theme. Can you please share your use case?

**Comment by Mione** [comment]
Hey,

I'm not saying it should be supported, it's just that it makes sense for the server to not throw a 500 when something like this happens. Especially with an error such as "Cannot read property '2' of null".

I don't believe you can expect everyone to read the documentation..

**Comment by kirrg001** [comment]
Alright, this was a misunderstanding. I thought you were suggesting to support it.

> it's just that it makes sense for the server to not throw a 500 when something like this happens. Especially with an error such as "Cannot read property '2' of null".

Yeah agree. A PR including a test is very welcome.
