### ISSUE TITLE
{{t}} helper not being recognised

### ISSUE THREAD

**Issue by CriticalRespawn** [TryGhost/gscan#95]
Despite being listed in the `knownHelpers` array here - https://github.com/TryGhost/gscan/blob/df8d7484ca968e60478c7e8765eeb656347ddc13/lib/spec.js

The {{t}} helper doesn't seem to be recognised and I get the following error once that scan has finished:

![https gscan ghost org](https://user-images.githubusercontent.com/37122500/37499452-b258926c-28bb-11e8-9524-96ccda7000f9.png)

I've tried this with some other helpers in that array and they work fine so it looks like it's just this one.

**Comment by kirrg001** [comment]
I assume `gscan.ghost.org` is not deployed with the latest version 🤔

**Comment by kirrg001** [comment]
> I assume gscan.ghost.org is not deployed with the latest version

Jup that's the problem.

**Comment by kirrg001** [comment]
http://gscan.ghost.org/ was updated. @CriticalRespawn please try again :)
And thanks for your report 🙈

**Comment by CriticalRespawn** [comment]
Tried it again, all works fine now!

Thanks for the quick resolution! 😄
