### ISSUE TITLE
links to /etc/passwd and /tmp

### ISSUE THREAD

**Issue by richRemer** [TryGhost/gscan#97]
Why are there symlinks to `/etc/passwd` and `/tmp` in the repo?  This is not safe.

**Comment by kevinansfield** [comment]
These are test fixtures to ensure that the module can protect against potentially unsafe symlinks. The test files will only be present when cloning the repo - they're listed in `.npmignore` to make sure they don't end up in the published module.

**Comment by richRemer** [comment]
That does not explain why the symlinks are pointing to globally used locations like `/tmp` and `/etc/passwd`.  Unless the test is poorly worded, the fact that the symlink is pointing to `/etc/passwd` is irrelevant; what's important to the test is that it is a symlink.  Why not point to a file within the repo?

**Comment by kirrg001** [comment]
@richRemer Yeah these test files should link to something in the repo. Thanks for the PR 👍
