### ISSUE TITLE
Add deprecations for single author usages

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/gscan#99]
We are about to ship [multiple authors](https://github.com/TryGhost/Ghost/pull/9426).

We would like to add new deprecations after the release.

- detect `include=author` in {{get}} helper
- detect `{{author}}` (and all more single author object usages)
- detect `filter=author:name`
- detect `filter=author:[...]`
- ...

**Comment by CriticalRespawn** [comment]
Hi @kirrg001 😄 

I've just created a PR with some work I've done for this in. I'll have more time to work on it over the weekend but thought I'd get a PR pushed up to Github now so you can check it out, if you have time. 

Hope this is okay?

**Comment by AileenCGN** [comment]
Hey @kirrg001 

A few things, just to make it clear to me:

*Deprecated in Multiple Authors* that seem clear (are they correct?):
- [ ] `{{#get "posts" include="author"}}` should be `{{#get "posts" include="authors"}}`
- [ ] `{{#author}}{{/author}}` should be `{{#authors}}{{/authors}}`
- [ ] `{{author}}` should be `{{authors}}`
- [ ] `{{author.*}}` should be `{{primary_author.*}}`

## But what about:
- [ ] `{{#has author="count:>1"}}`
- [ ] `{{#is author}}`
- [ ] `{{#if author}}`
- [ ] `{{#author}}` in `author.hbs`

**Comment by kirrg001** [comment]
Sorry the issue summary was written while i was coding multiple authors.

> {{#has author="count:>1"}}

See https://github.com/TryGhost/Ghost/issues/9530.

> {{#is author}}

This helper is a context helper. There is a still a single author template. Stays as is.

> {{#if author}}

This is probably used in a post context. So must be primary_author or authors. 
Same as `author.bio` -> `primary_author.bio`. OR authors[..].

> {{#author}} in author.hbs

Stays as is.

**Comment by kirrg001** [comment]
There is also:

- `field=author`
- `filter=author`

**Comment by AileenCGN** [comment]
@kirrg001 

> `field=author`

I'm sorry, but can you point me to where this is used? I can't seem to find it.

> `filter=author..`

For this I assume, it would need to be `primary_author` or `authors[n]...`

One more question that I have is more regarding old checks and wording, like for example the `author.image` check. For this we recommend to replace it to `author.profile_image` which is no longer true for 2.0, as it would need to `authors[n].profile_image` or `primary_author.profile_image`. There are a couple of checks we probably need to update. Do you agree?

**Comment by kirrg001** [comment]
> For this I assume, it would need to be primary_author or authors[n]...

Everything is explained on https://themes.ghost.org/docs/get.

> I'm sorry, but can you point me to where this is used? I can't seem to find it.

`field` is a parameter you can use to reduce the response.

`field=primary_author&include=authors`

**Comment by kirrg001** [comment]
Closed via https://github.com/TryGhost/gscan/commit/058e4d63f254df0920f1b257a4992acfed13a476.
